site_name: Roznaje
repo_url: https://github.com/roznaje/roznaje.github.io/

theme:
  name: mkdocs
  custom_dir: templates
  use_directory_urls: false

plugins:
  - search
  - mkdocs-backlinks

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true



